### ISSUE TITLE
English - Design-Local-page

### ISSUE THREAD

**Issue by vunyin** [lydenchai/Fresh-News#10]
- menu already exists on the homepage
- List all the link information 
- Footer already exists
https://en.freshnewsasia.com/index.php/en/localnews.html

**Comment by vantheav** [comment]
@lydenchai Could you help explain me more about my task? as now I did not understand any more.

**Comment by lydenchai** [comment]
@vantheav just wanted you to design a local page and list some data in English like the one below.


![Image](https://github.com/lydenchai/Fresh-News-group-04/assets/74000032/fd255e8b-63e5-443d-be9d-4e014b0cd598)
